name = "uart_boot_loader"
description = "UART boot loader"
version = "0.1.0-dev"

authors = ["J. German Rivera"]
maintainers = ["J. German Rivera <jgrivera67@gmail.com>"]
maintainers-logins = ["jgrivera67"]

executables = ["uart_boot_loader"]

[[depends-on]]
gnat_aarch64_elf = "*"
gnatprove = "*"
gprbuild = "*" # needed by alire-index CI builds

[gpr-set-externals]
CPU_Core = "arm_cortex_a72"

[[actions]]
[actions.'case(os)'.windows]
[actions.'case(os)'.'...']
type = "post-build"
command = ["sh", "-c", "aarch64-elf-objdump -dSstl bin/uart_boot_loader.elf > bin/uart_boot_loader.lst; aarch64-elf-objcopy -O binary bin/uart_boot_loader.elf bin/uart_boot_loader.bin"]
